import { MathProblem, PhonicsExercise, SightWord, Badge } from './types';

export const INITIAL_BADGES: Badge[] = [
  {
    id: 'first_star',
    title: 'First Shining Star',
    description: 'Solved your very first learning challenge!',
    icon: '⭐',
    category: 'general',
    unlockedAt: new Date().toISOString(),
  },
  {
    id: 'math_wizard_1',
    title: 'Counting Champion',
    description: 'Mastered counting objects up to 10 with ease.',
    icon: '🍎',
    category: 'math',
  },
  {
    id: 'math_plus_star',
    title: 'Addition Adventurer',
    description: 'Solved 10 addition challenges with visual counters.',
    icon: '➕',
    category: 'math',
  },
  {
    id: 'phonics_explorer',
    title: 'Letter Sound Explorer',
    description: 'Found all short vowel letter sounds.',
    icon: '🔤',
    category: 'phonics',
  },
  {
    id: 'sight_word_scout',
    title: 'Sight Word Super Scout',
    description: 'Mastered 10 beginner sight words.',
    icon: '👁️',
    category: 'sight_words',
  },
  {
    id: 'story_creator',
    title: 'Master Storyteller',
    description: 'Wove your first magical story chapter with AI.',
    icon: '📖',
    category: 'storytelling',
  },
  {
    id: 'streak_3',
    title: '3-Day Brain Streak',
    description: 'Practiced 3 days in a row like a true scholar.',
    icon: '🔥',
    category: 'general',
  },
];

export const STARTER_MATH_PROBLEMS: MathProblem[] = [
  {
    id: 'math_1',
    level: 1,
    type: 'counting',
    prompt: 'How many juicy apples can you count in the basket?',
    visualEmoji: '🍎',
    visualCountA: 4,
    options: [2, 4, 5],
    correctAnswer: 4,
    explanation: 'Count with your finger: 1, 2, 3, 4! There are 4 apples.',
    stepByStep: ['Point to the first apple: 1', 'Point to the next: 2', 'Point to the next: 3', 'Point to the last: 4! Total is 4.'],
    manipulativeType: 'objects',
  },
  {
    id: 'math_2',
    level: 1,
    type: 'counting',
    prompt: 'Count the playful puppies playing in the park!',
    visualEmoji: '🐶',
    visualCountA: 6,
    options: [5, 6, 7],
    correctAnswer: 6,
    explanation: 'Let us count them together: 1, 2, 3, 4, 5, 6 puppies!',
    stepByStep: ['1 🐶', '2 🐶', '3 🐶', '4 🐶', '5 🐶', '6 🐶! Total is 6.'],
    manipulativeType: 'objects',
  },
  {
    id: 'math_3',
    level: 2,
    type: 'addition',
    prompt: 'You have 3 stars ⭐ and your bunny friend gives you 2 more ⭐. How many stars in all?',
    visualEmoji: '⭐',
    visualCountA: 3,
    visualCountB: 2,
    options: [4, 5, 6],
    correctAnswer: 5,
    explanation: '3 stars plus 2 stars equals 5 stars!',
    stepByStep: ['Start with 3: ⭐ ⭐ ⭐', 'Add 2 more: ⭐ ⭐', 'Count all together: 1, 2, 3, 4, 5!'],
    manipulativeType: 'ten_frame',
  },
  {
    id: 'math_4',
    level: 2,
    type: 'addition',
    prompt: '2 yummy cupcakes 🧁 plus 4 sweet donuts 🍩. How many treats total?',
    visualEmoji: '🧁',
    visualCountA: 2,
    visualCountB: 4,
    options: [5, 6, 7],
    correctAnswer: 6,
    explanation: '2 + 4 = 6 tasty treats in total!',
    stepByStep: ['Start with 2: 🧁 🧁', 'Count on 4 more: 3, 4, 5, 6!', 'Total treats = 6.'],
    manipulativeType: 'objects',
  },
  {
    id: 'math_5',
    level: 3,
    type: 'subtraction',
    prompt: 'There were 5 balloons 🎈 in the sky. 2 floated away 💨. How many balloons are left?',
    visualEmoji: '🎈',
    visualCountA: 5,
    visualCountB: 2,
    options: [2, 3, 4],
    correctAnswer: 3,
    explanation: '5 take away 2 leaves 3 balloons!',
    stepByStep: ['Start with all 5 balloons: 🎈🎈🎈🎈🎈', 'Take away 2 balloons: ❌ ❌', 'Count what is left: 1, 2, 3! Answer is 3.'],
    manipulativeType: 'objects',
  },
  {
    id: 'math_6',
    level: 4,
    type: 'early_mult',
    prompt: 'There are 2 nests 🪺. Each nest has 3 little blue eggs 🪺. How many eggs in all?',
    visualEmoji: '🥚',
    visualCountA: 2,
    visualCountB: 3,
    options: [5, 6, 8],
    correctAnswer: 6,
    explanation: '2 groups of 3 is 3 + 3 = 6 eggs!',
    stepByStep: ['First nest: 🥚🥚🥚 (3)', 'Second nest: 🥚🥚🥚 (3)', 'Count together: 3 + 3 = 6! That is 2 groups of 3!'],
    manipulativeType: 'groups',
  },
];

export const STARTER_PHONICS_EXERCISES: PhonicsExercise[] = [
  {
    id: 'phonics_1',
    sound: 'a',
    soundExample: 'short /æ/ like in apple',
    audioPronunciation: 'ah',
    targetWord: 'CAT',
    missingLetterIndex: 1,
    letterChoices: ['A', 'O', 'U'],
    imageEmoji: '🐱',
    rhymingWords: ['BAT', 'HAT', 'MAT'],
    clue: 'A furry pet that says meow! C - ___ - T',
  },
  {
    id: 'phonics_2',
    sound: 'u',
    soundExample: 'short /ʌ/ like in up',
    audioPronunciation: 'uh',
    targetWord: 'SUN',
    missingLetterIndex: 1,
    letterChoices: ['U', 'E', 'I'],
    imageEmoji: '☀️',
    rhymingWords: ['RUN', 'FUN', 'BUN'],
    clue: 'Shines bright in the sky during the day! S - ___ - N',
  },
  {
    id: 'phonics_3',
    sound: 'i',
    soundExample: 'short /ɪ/ like in igloo',
    audioPronunciation: 'ih',
    targetWord: 'PIG',
    missingLetterIndex: 1,
    letterChoices: ['I', 'A', 'O'],
    imageEmoji: '🐷',
    rhymingWords: ['BIG', 'DIG', 'WIG'],
    clue: 'A pink animal on a farm that says oink! P - ___ - G',
  },
  {
    id: 'phonics_4',
    sound: 'o',
    soundExample: 'short /ɒ/ like in octopus',
    audioPronunciation: 'aw',
    targetWord: 'DOG',
    missingLetterIndex: 1,
    letterChoices: ['O', 'E', 'U'],
    imageEmoji: '🐶',
    rhymingWords: ['FOG', 'LOG', 'FROG'],
    clue: 'Man\'s best friend who wags his tail! D - ___ - G',
  },
  {
    id: 'phonics_5',
    sound: 'e',
    soundExample: 'short /ɛ/ like in elephant',
    audioPronunciation: 'eh',
    targetWord: 'BED',
    missingLetterIndex: 1,
    letterChoices: ['E', 'A', 'I'],
    imageEmoji: '🛏️',
    rhymingWords: ['RED', 'FED', 'SLED'],
    clue: 'Where Raena sleeps cozy at night! B - ___ - D',
  },
  {
    id: 'phonics_6',
    sound: 'sh',
    soundExample: 'digraph /ʃ/ like in shell',
    audioPronunciation: 'shhh',
    targetWord: 'SHIP',
    missingLetterIndex: 0,
    letterChoices: ['SH', 'CH', 'TH'],
    imageEmoji: '🚢',
    rhymingWords: ['CHIP', 'TRIP', 'DIP'],
    clue: 'Sails across the deep blue ocean! ___ - I - P',
  },
];

export const STARTER_SIGHT_WORDS: SightWord[] = [
  {
    id: 'sw_1',
    word: 'THE',
    category: 'pre-primer',
    sentence: 'Raena saw the friendly puppy.',
    audioExample: 'The',
    scrambledLetters: ['T', 'H', 'E'],
    emoji: '👉',
  },
  {
    id: 'sw_2',
    word: 'SEE',
    category: 'pre-primer',
    sentence: 'I can see the bright rainbow in the sky.',
    audioExample: 'See',
    scrambledLetters: ['S', 'E', 'E'],
    emoji: '👀',
  },
  {
    id: 'sw_3',
    word: 'CAN',
    category: 'pre-primer',
    sentence: 'Raena can jump super high!',
    audioExample: 'Can',
    scrambledLetters: ['C', 'A', 'N'],
    emoji: '💪',
  },
  {
    id: 'sw_4',
    word: 'LIKE',
    category: 'pre-primer',
    sentence: 'I like sweet strawberries and books.',
    audioExample: 'Like',
    scrambledLetters: ['L', 'I', 'K', 'E'],
    emoji: '❤️',
  },
  {
    id: 'sw_5',
    word: 'PLAY',
    category: 'pre-primer',
    sentence: 'Let us play in the sunshine together.',
    audioExample: 'Play',
    scrambledLetters: ['P', 'L', 'A', 'Y'],
    emoji: '🛝',
  },
  {
    id: 'sw_6',
    word: 'MY',
    category: 'pre-primer',
    sentence: 'This is my cute bunny companion!',
    audioExample: 'My',
    scrambledLetters: ['M', 'Y'],
    emoji: '✨',
  },
  {
    id: 'sw_7',
    word: 'YOU',
    category: 'pre-primer',
    sentence: 'You are doing a fantastic job!',
    audioExample: 'You',
    scrambledLetters: ['Y', 'O', 'U'],
    emoji: '🌟',
  },
  {
    id: 'sw_8',
    word: 'BIG',
    category: 'pre-primer',
    sentence: 'Look at the big friendly dinosaur.',
    audioExample: 'Big',
    scrambledLetters: ['B', 'I', 'G'],
    emoji: '🦕',
  },
];

export const STARTER_STORY_PROMPTS = [
  {
    id: 'story_1',
    theme: 'Enchanted Forest Animal Friends',
    title: 'The Magic Acorn & Barnaby Bunny',
    coverEmoji: '🐰',
    initialStarter: 'One sunny morning, Barnaby Bunny hopped into the whispering green forest. Under a sparkling mushroom, he found a glowing golden acorn that softly giggled! What should Barnaby do with the magical acorn?',
    suggestedWords: ['pick it up', 'talk to it', 'give it to squirrel', 'put in pocket'],
  },
  {
    id: 'story_2',
    theme: 'Space Discovery Adventure',
    title: 'Raena\'s Glittering Rocket Ship',
    coverEmoji: '🚀',
    initialStarter: '3... 2... 1... Blastoff! Raena and her robot puppy Pip zoomed past Mars and discovered a planet made entirely of rainbow marshmallows. Suddenly, a little alien with three eyes waved hello! What does Raena say or do?',
    suggestedWords: ['wave hello', 'share a cookie', 'ask his name', 'dance together'],
  },
  {
    id: 'story_3',
    theme: 'Garden Mystery & Little Dragon',
    title: 'The Teacup Dragon in the Flowerbed',
    coverEmoji: '🐉',
    initialStarter: 'While watering the sunflowers in the garden, Raena heard a tiny sneeze: "Achoo!" Out from behind a pink tulip popped a tiny baby dragon the size of an apple! He looked hungry. What treat can we offer him?',
    suggestedWords: ['a sweet strawberry', 'a warm leaf', 'some water', 'a flower petal'],
  },
];
